name: C/C++ CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y libxml2-dev libpng12-dev zlib1g-dev libcunit1-dev doxygen
    - run: mkdir m4
    - run: autoreconf -fi
    - run: ./configure --disable-root-actions --with-noaaport
    - run: make
    - run: make check
    - run: make distcheck
